name: Cross-compilation

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Stonenet
      uses: actions/checkout@v3
    - name: Clear disk space
      run: |
        rm -rf /opt/hostedtoolcache
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    # This job currently fails on github because of disk space issues no their servers
    - name: Cross compile for Debian armhf
      run: |
        docker build . --build-arg target=armhf
    - name: Cross compile for Windows amd64
      run: |
        docker build . --build-arg target=win64
