name: Linux

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Stonenet
      uses: actions/checkout@v3
    - name: Run tests (debug)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test --verbose
    - name: Run tests (release)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test --verbose --release
    - name: Install webkit2gtk
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.1-dev
    - name: Run desktop client tests (debug)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test -p stonenet-desktop --verbose
    - name: Run desktop client tests (release)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test -p stonenet-desktop --verbose --release
    - name: Install Nix
      run: sudo apt-get install -y nix-bin
    - name: Build daemon with Nix
      run: sudo nix --extra-experimental-features 'nix-command flakes' build
    - name: Build desktop client with Nix
      run: sudo nix --extra-experimental-features 'nix-command flakes' build .#desktop
