name: Linux

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Stonenet
      uses: actions/checkout@v3
    - name: Run tests (debug)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test --verbose -- --test-threads 1
    - name: Run tests (release)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test --verbose --release -- --test-threads 3
    - name: Install webkit2gtk
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.1-dev
    - name: Run desktop client tests (debug)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test -p stonenet-desktop --verbose
    - name: Run desktop clienttests (release)
      run: RUST_BACKTRACE=full RUST_LOG=debug cargo test -p stonenet-desktop --verbose --release
    - name: Install Nix
      run: sudo apt-get install -y nix-bin
    - name: Build daemon with Nix
      run: sudo nix --extra-experimental-features 'nix-command flakes' build
    - name: Build desktop client with Nix
      run: sudo nix --extra-experimental-features 'nix-command flakes' build .#desktop
    - name: Clear disk space
      run: rm -rf /opt/hostedtoolcache
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    # This job currently fails on github because of disk space issues no their servers
    - name: Cross compile binaries
      run: |
        docker build package --build-arg target=armhf
        docker build package --build-arg target=win64
