name: Windows

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Checkout Stonenet
        uses: actions/checkout@v3
      - name: Build (debug)
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Build (debug)
        uses: actions-rs/cargo@v1
        with:
          command: test
        continue-on-error: true
      - name: Build (release)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Build (release)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
        continue-on-error: true
      - name: Run tests for desktop client (debug)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p stonenet-desktop
        # Browser-Window compilation on Windows is broken for the commit that is pinned in stonenet-desktop
        continue-on-error: true
      - name: Run tests for desktop client (release)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p stonenet-desktop --release
        continue-on-error: true
